version: '3.1'
services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    restart: unless-stopped
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
    networks:
      mynetwork:
        ipv4_address: 172.18.0.2

  app:
    container_name: app
    depends_on:
      - mysqldb
    build: ./
    image: firaskill12/achat-image:latest
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_PROFILES_ACTIVE: prod,actuator
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: prometheus
    networks:
      mynetwork:
        ipv4_address: 172.18.0.3

  front:
    container_name: front
    build: ./
    image: firaskill12/front-image:1.0.0
    ports:
      - 4200:80
    depends_on:
      - app
    networks:
      mynetwork:
        ipv4_address: 172.18.0.4

volumes:
  db:
    
networks:
  mynetwork:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
