version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    container_name: mysqldb
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=achatdb
    ports:
      - 3307:3306
    volumes:
      - db:/var/lib/mysql
  app:
    container_name: app
    depends_on:
      - mysqldb
    build: ./
    image: firaskill12/achat-image:1.0.0
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{}'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true
  front:
    container_name: front
    build: ./
    image: firaskill12/front-image:1.0.0
    ports:
      - 4200:80

volumes:
  db:
