version: '3.7'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=achatdb
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - net

  app-backend:
    image: montassargaida/devops:${DOCKERTAG}
    ports:
      - 8088:8088
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/achatdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=
    depends_on:
      - db
    networks:
      - net

  frontend:
    image: montassargaida/devops:frontend
    ports:
      - 4200:4200
    depends_on:
      - app-backend
    networks:
      - net
networks:
  net:

volumes:
  db-data:
